import index from '../generated/work-index.json';
import { CATEGORIES } from './content-schema.mjs';

export type CategoryKey = (typeof CATEGORIES)[number]['key'];

export type Media = { src: string; alt: string };
export type Video = { title?: string; src?: string; url?: string; poster?: string };

export type Project = {
  slug: string;
  title: string;
  category: CategoryKey;
  year: string;
  runtime: string;
  role: string;
  status: string;
  logline: string;
  hero: Media;
  stills: Media[];
  videos: Video[];
};

export const categories: { key: CategoryKey; label: string }[] = CATEGORIES;

/** Generated by scripts/build-content-index.mjs from content/work/*; already sorted newest first. */
export const sortedProjects: Project[] = index.projects as Project[];

export const skills = ['Directing', 'Writing', 'Cinematography', 'Editing', 'Colour'];

export const skillsFull = [
  'Directing',
  'Screenwriting',
  'Cinematography',
  'Editing',
  'Colour grading',
  'Casting',
  'Working with actors',
  'Storyboarding',
  'Premiere Pro',
  'DaVinci Resolve',
];

export const experience = [
  { year: '2025', title: 'The Quiet Hours', role: 'Director' },
  { year: '2025', title: 'Field Notes — brand film', role: 'Director' },
  { year: '2024', title: 'Paper Houses', role: 'Writer / Director' },
  { year: '2024', title: 'Glasshouse — music video', role: 'Director' },
  { year: '2022', title: 'Northbound', role: 'Director / Editor' },
];

export function catLabel(key: string): string {
  return categories.find((c) => c.key === key)?.label ?? key;
}

export function findProject(slug: string): Project | undefined {
  return sortedProjects.find((p) => p.slug === slug);
}

export function filterProjects(filter: string): Project[] {
  return filter === 'all' ? sortedProjects : sortedProjects.filter((p) => p.category === filter);
}

export function isFilterKey(value: string | null | undefined): value is CategoryKey {
  return categories.some((c) => c.key === value);
}

export function neighbours(slug: string): { prev: Project; next: Project } {
  const idx = Math.max(
    0,
    sortedProjects.findIndex((p) => p.slug === slug),
  );
  const n = sortedProjects.length;
  return { prev: sortedProjects[(idx - 1 + n) % n], next: sortedProjects[(idx + 1) % n] };
}
